htdocs/src/DemandeBundle/Entity/Colisage.php
<?php

namespace DemandeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="colisage")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap( {"list_grume" = "ColisageGrume", "list_botte" = "ColisageBotte", "list_paquet" = "ColisagePaquet"} )
 */
abstract class Colisage
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

   /**
    * @ORM\ManyToOne(targetEntity="ExploitationBundle\Entity\Essence" ,cascade={"persist"})
    * 
    */
    protected $essence;

    /**
     * @var array
     *
     * 
     */
    protected $liste;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Set liste
     *
     * @param string $liste
     * @return Colisage
     */
    public function setListe($liste)
    {
        $this->liste = $liste;

        return $this;
    }

    /**
     * Get liste
     *
     * @return string 
     */
    public function getListe()
    {
        return $this->liste;
    }

    /**
     * Add liste
     *
     * @param \DemandeBundle\Entity\Produit $liste
     * @return Liste_grume
     */
    public function addListe(\DemandeBundle\Entity\Produit $liste)
    {
        $this->liste[] = $liste;
        $liste->setColisage($this);
        return $this;
 
    }

    /**
     * Remove liste
     *
     * @param \DemandeBundle\Entity\Produit $liste
     */
    public function removeListe(\DemandeBundle\Entity\Produit $liste)
    {
        $this->liste->removeElement($liste);
        $liste->setColisage(null);

    }


    public function setBoisEssence()
    {
        /** @var Produit $bois */
        foreach ($this->liste as $bois) {
            $bois->setEssence($this->essence);
        }
    }


    /**
     * Set essence
     *
     * @param \ExploitationBundle\Entity\Essence $essence
     * @return Colisage
     */
    public function setEssence(\ExploitationBundle\Entity\Essence $essence = null)
    {
        $this->essence = $essence;

        return $this;
    }

    /**
     * Get essence
     *
     * @return \DemandeBundle\Entity\Essence 
     */
    public function getEssence()
    {
        return $this->essence;
    }

    public function getCubage(){
        $c= 0.0;
        /** @var Produit $p */
        foreach ($this->liste as $p) {
            $c += (double) $p->getCubage();
        }

        return $c;
    }
}

htdocs/src/DemandeBundle/Entity/Grume.php
<?php

namespace DemandeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Grume
 *
 * @ORM\Entity()
 */
class Grume extends Produit
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="num_grume", type="string", length=255)
     */
    private $numGrume;

    /**
     * @var string
     *
     * @ORM\Column(name="num_abattage", type="string", length=255)
     */
    private $numAbattage;

    /**
     * @var string
     *
     * @ORM\Column(name="num_permis", type="string", length=255)
     */
    private $numPermis;

    /**
     * @var string
     *
     * @ORM\Column(name="longueur", type="decimal", precision=10, scale=1)
     */
    private $longueur;

    /**
     * @var int
     *
     * @ORM\Column(name="diamAA", type="decimal", precision=10, scale=3)
     */
    private $diamAA;

    /**
     * @var int
     *
     * @ORM\Column(name="diamSA", type="decimal", precision=10, scale=3)
     */
    private $diamSA;

     /**
     * @var string
     *
     * @ORM\Column(name="tonnage", type="decimal", precision=10, scale=3)
     */
    private $tonnage;

    /**
     * @var Colisage
     *
     * @ORM\ManyToOne(targetEntity="DemandeBundle\Entity\ColisageGrume",inversedBy="liste")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $colisage;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set numGrume
     *
     * @param string $numGrume
     * @return Grume
     */
    public function setNumGrume($numGrume)
    {
        $this->numGrume = $numGrume;

        return $this;
    }

    /**
     * Get numGrume
     *
     * @return string 
     */
    public function getNumGrume()
    {
        return $this->numGrume;
    }

    /**
     * Set numAbattage
     *
     * @param string $numAbattage
     * @return Grume
     */
    public function setNumAbattage($numAbattage)
    {
        $this->numAbattage = $numAbattage;

        return $this;
    }

    /**
     * Get numAbattage
     *
     * @return string 
     */
    public function getNumAbattage()
    {
        return $this->numAbattage;
    }

    /**
     * Set numPermis
     *
     * @param string $numPermis
     * @return Grume
     */
    public function setNumPermis($numPermis)
    {
        $this->numPermis = $numPermis;

        return $this;
    }

    /**
     * Get numPermis
     *
     * @return string 
     */
    public function getNumPermis()
    {
        return $this->numPermis;
    }

    /**
     * Set longueur
     *
     * @param string $longueur
     * @return Grume
     */
    public function setLongueur($longueur)
    {
        $this->longueur = $longueur;

        return $this;
    }

    /**
     * Get longueur
     *
     * @return string 
     */
    public function getLongueur()
    {
        return $this->longueur;
    }

    /**
     * Set diamAA
     *
     * @param integer $diamAA
     * @return Grume
     */
    public function setDiamAA($diamAA)
    {
        $this->diamAA = $diamAA;

        return $this;
    }

    /**
     * Get diamAA
     *
     * @return integer 
     */
    public function getDiamAA()
    {
        return $this->diamAA;
    }

    /**
     * Set diamSA
     *
     * @param integer $diamSA
     * @return Grume
     */
    public function setDiamSA($diamSA)
    {
        $this->diamSA = $diamSA;

        return $this;
    }

    /**
     * Get diamSA
     *
     * @return integer 
     */
    public function getDiamSA()
    {
        return $this->diamSA;
    }

    /**
     * Set cubage
     *
     * @param string $cubage
     * @return Bottes
     */
    public function setCubage($cubage){}

    /**
     * Get cubage
     *
     * @return string 
     */

    public function getCubage(){
        return $this->calcul($this->diamAA);
    }

     public function getCubageSA(){
        return $this->calcul($this->diamSA);
    }

    private function calcul($d){

        $v = $this->longueur * $d * $d * (pi()/4) * pow(10,-4);
        return number_format($v,3,'.',',');
    }

    /**
     * Set tonnage
     *
     * @param string $tonnage
     * @return Bottes
     */
    public function setTonnage($tonnage)
    {
        $this->tonnage = $tonnage;

        return $this;
    }

    /**
     * Get tonnage
     *
     * @return string 
     */
    public function getTonnage()
    {
        return $this->tonnage;
    }

    public function __toString(){
        return ($this->getId())? "Grume: ".$this->getNumAbattage()." ".$this->getEssence():"N/A";
    }

}

htdocs/src/DemandeBundle/Resources/views/Colisage/botte.html.twig
{% extends "DemandeBundle:CRUD:colisage_show.html.twig" %}

{% block thead %}
<tr>
    <th>No.</th>
    <th>Nombre des bottes</th>
    <th>Nombre des pièces</th>
    <th>Epaisseur (mm)</th>
    <th>Qualité</th>
    <th>Cubage (m3)</th>
    <th>Tonnage</th>
</tr>
{% endblock thead %}

{% block item %}
    <td>{{ loop.index }}</td>
    <td>{{ item.nbreBotte }}</td>
    <td>{{ item.nbrePiece }}</td>
    <td>{{ item.epaisseur }}</td>
    <td>{{ item.qualite }}</td>
    <td>{{ item.cubage }}</td>
    <td>{{ item.tonnage }}</td>
{% endblock %}

htdocs/src/DemandeBundle/Resources/views/Colisage/grume.html.twig
{% extends "DemandeBundle:CRUD:colisage_show.html.twig" %}

{% block thead %}
<tr>
    <th>No.</th>
    <th>N° Grume</th>
    <th>N° Abattage</th>
    <th>Permis de Coupe</th>
    <th>Longueur (m)</th>
    <th>Diamètre AA (cm)</th>
    <th>Diamètre SA (cm)</th>
    <th>Volume AA (m3)</th>
    <th>Volume SA (m2)</th>
    <th>Tonnage (T)</th>
</tr>
{% endblock thead %}

{% block item %}
    <td>{{ loop.index }}</td>
    <td>{{ item.numGrume }}</td>
    <td>{{ item.numAbattage }}</td>
    <td>{{ item.numPermis }}</td>
    <td>{{ item.longueur }}</td>
    <td>{{ item.diamAA }}</td>
    <td>{{ item.diamSA }}</td>
    <td>{{ item.cubage }}</td>
    <td>{{ item.cubageSA }}</td>
    <td>{{ item.tonnage }}</td>
{% endblock %}

htdocs/src/DemandeBundle/Resources/views/Colisage/paquet.html.twig
{% extends "DemandeBundle:CRUD:colisage_show.html.twig" %}

{% block thead %}
<tr>
    <th>No.</th>
    <th>Nombre des Paquets</th>
    <th>Nombre des pièces</th>
    <th>Hauteur (m)</th>
    <th>Largeur (m)</th>
    <th>Epaisseur (m)</th>
    <th>Tonnage</th>
</tr>
{% endblock thead %}

{% block item %}
    <td>{{ loop.index }}</td>
    <td>{{ item.nbrePaquet }}</td>
    <td>{{ item.piece }}</td>
    <td>{{ item.hauteur }}</td>
    <td>{{ item.largeur }}</td>
    <td>{{ item.epaisseurP }}</td>
    <td>{{ item.cubage }}</td>
{% endblock %}